version: '2'

services:
  front-end:
    image: registry.alauda.cn/chennanfei/weaver-front-end
    ports:
      - '80:8079'
    environment:
      - reschedule=on-node-failure
  catalogue:
    image: registry.alauda.cn/chennanfei/weaver-catalogue
    environment:
      - reschedule=on-node-failure
  catalogue-db:
    image: registry.alauda.cn/chennanfei/weaver-catalogue-db
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  carts:
    image: registry.alauda.cn/chennanfei/weaver-carts
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  carts-db:
    image: registry.alauda.cn/chennanfei/weaver-mongo
    environment:
      - reschedule=on-node-failure
  orders:
    image: registry.alauda.cn/chennanfei/weaver-orders
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  orders-db:
    image: registry.alauda.cn/chennanfei/weaver-mongo
    environment:
      - reschedule=on-node-failure
  shipping:
    image: registry.alauda.cn/chennanfei/weaver-shipping
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  rabbitmq:
    image: registry.alauda.cn/chennanfei/weaver-rabbitmq:3
    environment:
      - reschedule=on-node-failure
  payment:
    image: registry.alauda.cn/chennanfei/weaver-payment
    environment:
      - reschedule=on-node-failure
  user:
    image: registry.alauda.cn/chennanfei/weaver-user
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
  user-db:
    image: registry.alauda.cn/chennanfei/weaver-user-db
    environment:
      - reschedule=on-node-failure
  user-sim:
    image: registry.alauda.cn/chennanfei/weaver-load-test
    command: "-d 60 -r 200 -c 2 -h front-end"
